version: '3.4'

services:
  authenticationservice:
    restart: always
    build:
      context: ./Backend
      dockerfile: AuthenticationService/Dockerfile
    ports:
      - 5000:5000
    depends_on:
       - db
  frontend:
    restart: always
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
     - 80:80
    depends_on: 
     - authenticationservice
  db:
    image: postgres
    restart: always
    ports:
      - 5001:5432
    volumes:
      - /Docker/AuthenticationDB:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: AuthenticationDB