version: '3.4'

services:
  authenticationservice:
    image: ${DOCKER_REGISTRY-}authenticationservice
    restart: always
    build:
      context: ./Backend
      dockerfile: AuthenticationService/Dockerfile
    ports:
      - 5000:5000
    depends_on:
       - db
  frontend:
    image: ${DOCKER_REGISTRY-}frontend
    restart: always
    environment:
      REACT_APP_SERVER_URL: "localhost:6000"
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
     - 80:80
    depends_on: 
     - authenticationservice
  db:
    image: postgres
    restart: always
    ports:
      - 5001:5432
    volumes:
      - /Docker/postgres-data:/var/lib/postgresql/data
    environment:
        POSTGRES_PASSWORD: pass
        POSTGRES_USER: user
        POSTGRES_DB: AuthenticationDB
