version: 1
jobs:
  backend_build:
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet restore
      - run: cd Backend && dotnet build
  backend_test:
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet test
  frontend_build:
    docker:
      - image: circleci/node:8.9.1
    steps:
      - checkout
      - run: cd Frontend && npm run build

workflows:
  version: 2
  build:
    jobs:
      - backend_build
      - backend_test:
          requires:
            - backend_build
      - frontend_build