version: 1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout
      - run: find .
      - run: cd Backend && dotnet restore
      - run: cd Backend && dotnet build
      - run: cd Backend && dotnet test