version: 1
jobs:
  build:
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout:
        path: ~/Backend
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test