version: 1
jobs:
  backend_build:
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet restore
      - run: cd Backend && dotnet build
  backend_test:
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout
      - run: cd Backend && dotnet test
workflows:
  version: 2
  build:
    jobs:
      - backend_build
      - backend_test