version: 1
jobs:
  build:
    working_directory: Backend/
    docker:
      - image: microsoft/dotnet:2.1.500-sdk-stretch
    steps:
      - checkout
      - run: pwd
      - run: find .
      - run: dotnet restore
      - run: dotnet build
      - run: dotnet test